export * from './patient.repository'
export * from './room.repository'
export * from './category.repository'
export * from './product-service.repository'
export * from './partner.repository'
export * from './appointment.repository'
export * from './notification.repository'